export enum ArticleCategory {
  CONSEILS_TECHNIQUES = 'CONSEILS_TECHNIQUES',
  REALISATIONS = 'REALISATIONS',
  BUDGET_PLANIFICATION = 'BUDGET_PLANIFICATION',
  ARCHITECTURE_FINITIONS = 'ARCHITECTURE_FINITIONS',
  SUIVI_CHANTIER = 'SUIVI_CHANTIER',
}

