export enum LeadStatus {
  NOUVEAU = 'NOUVEAU',
  CONTACTE = 'CONTACTE',
  VISITE_PLANIFIEE = 'VISITE_PLANIFIEE',
  DEVIS_ENVOYE = 'DEVIS_ENVOYE',
  NEGOCIATION = 'NEGOCIATION',
  CONVERTI = 'CONVERTI',
  PERDU = 'PERDU',
}

