export enum PartnershipType {
  FOURNISSEUR = 'FOURNISSEUR',
  ENTREPRISE_DE_SERVICES = 'ENTREPRISE_DE_SERVICES',
  PARTENAIRE_COMMERCIAL = 'PARTENAIRE_COMMERCIAL',
  COLLABORATION_STRATEGIQUE = 'COLLABORATION_STRATEGIQUE',
  AUTRE = 'AUTRE',
}
