export enum ProjectStep {
  
    VISITE_TECHNIQUE = 'VISITE_TECHNIQUE',
    DEVIS_DETAILLE = 'DEVIS_DETAILLE',
    PLANIFICATION = 'PLANIFICATION',
    EXECUTION_SUPERVISEE = 'EXECUTION_SUPERVISEE',
    FINITIONS_VERIFICATION = 'FINITIONS_VERIFICATION',
    LIVRAISON_GARANTIE = 'LIVRAISON_GARANTIE',
}

